- name: bash
  src: https://github.com/deanmcniven/ansible-bash
  version: origin/master

- name: git
  src: https://github.com/deanmcniven/ansible-git
  version: origin/master

- name: moby
  src: https://github.com/deanmcniven/ansible-moby
  version: origin/master

- name: set-user-facts
  src: https://github.com/deanmcniven/ansible-set-user-facts
  version: origin/master

- name: tmux
  src: https://github.com/deanmcniven/ansible-tmux
  version: origin/master

- name: vim
  src: https://github.com/deanmcniven/ansible-vim
  version: origin/master

